# Generated by Django 3.2.3 on 2022-05-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donordetails',
            name='blood_group',
            field=models.CharField(max_length=4),
        ),
    ]
